# Programmer: Bruce Provencher
# Date: 15 MAR 2014
# Project: Get Home Town from User 

# Ask user which city s/he lives in
city = input ("Enter the name of the city you live in: ")

# Print out the name of the city

# We are using a STRING LITERAL and a VARIABLE
# to generate some output

# The STRING LITERAL in this instance is "You live in"
# The VARIABLE, in this example, is the variable 'city'

# The variable acts as a placeholder 
# so whatever the user enters as his city of residence
# will be added to the output generated by the line of code below

print ("You live in " + city)


